#data:
  #image: busybox
  #volumes:
    #- /data

server:
  build: .
  #image: mprokopov/manager.io
  volumes:
    - ./data:/data
  environment:
    - VIRTUAL_HOST=manager.dev
  #command: mono ManagerServer.exe -port 8080 -path '/data'
  #volumes_from:
    #- data
